### ISSUE TITLE
Readme info for installation

### ISSUE THREAD

**Issue by Berniep1** [matttturnbull/minilab3#1]
Hi,
Thank you very much for this tweak, this helps a lot.

Installation was a little bit tricky because of your folder info.
Correct folder in my Windows Ableton Live 11.3.21 version:
C:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts\MiniLab_3\

Your README:
> 2.  Navigate to your Control Surface directory:
> Windows: \Users\[Username]\AppData\Roaming\Ableton\Live x.x.x\Preferences\User Remote Scripts
> 3. Back up your /MiniLab_3 folder (keep a copy to revert to zipped up somewhere)

Bernie

**Comment by matttturnbull** [comment]
You're welcome, and thanks for the tip. Updated the Readme 👍
