### ISSUE TITLE
Add undo button?

### ISSUE THREAD

**Issue by styles01** [matttturnbull/minilab3#2]
Hey so I saw that you modified the loop and tap buttons. I think the most important feature to add is the undo; and I would love to have a version that replaces tap or loop (maybe as shift functions) with UNDO. It's crucial for live-looping. I'm wondering if you can help do that! Thanks. Also, does your implementation use the Firmware 1.11 version?

**Comment by matttturnbull** [comment]
Hey @styles01 , afraid I’m not working on this at the moment, but for sure Undo could be mapped to a button. Believe firmware is v1.11. If you’re interested in having a go, I’ve left some links in the readme.
